class: net.gtaun.shoebill.streamer.Streamer
name: Incognito's Streamer Wrapper Plugin
version: ${system.MAVEN_VERSION}
buildNumber: ${env.BUILD_NUMBER}
buildDate: ${env.BUILD_START_DATE}
authors: Marvin Haschker, valych